CREATE TABLE [dbo].[tbUsuarios]
(
	[USR_Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [AUT_Id] INT NOT NULL,
    [USR_Nome] VARCHAR (200) NOT NULL,
    [USR_Email] VARCHAR(100) NOT NULL, 
    [USR_Senha] VARCHAR(MAX) NOT NULL, 
    [USR_DataNascimento] DATETIME NOT NULL, 
    [USR_Sexo] INT NOT NULL 
)
