# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy GoAesthetic on Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build webapp with dotnet
        run: dotnet build --configuration Release ./Projeto/GoAesthetic/GoAesthetic.sln

      - name: dotnet publish webapp
        run: dotnet publish -c Release -o ./Projeto/publish/website ./Projeto/GoAesthetic/GoAesthetic.sln

      - name: Build api with dotnet
        run: dotnet build --configuration Release ./Projeto/GoAetheticApi/GoAetheticApi.sln

      - name: dotnet publish api
        run: dotnet publish -c Release -o ./Projeto/publish/api ./Projeto/GoAetheticApi/GoAetheticApi.sln

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./Projeto/publish
          retention-days: 1

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.WEBSITENAME}}
          slot-name: 'Production'
          publish-profile: ${{ secrets.WEBAPPSECRET }}
          package: ./website

      - name: Deploy to Azure API
        id: deploy-to-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.APINAME}}
          slot-name: 'Production'
          publish-profile: ${{ secrets.APISECRET }}
          package: ./api
